### PR TITLE
How we work: Engineering team practices & norms

### PR DESCRIPTION
**Pull request by alexsoble**
[Preview link.](https://github.com/18F/OPRE-MAPS/blob/ars/23/how-we-work-eng-practices/docs/how_we_work.md) 👁️ 

GitHub card: https://github.com/18F/OPRE-MAPS/issues/23.

Content via [[draft] Engineering team practices & norms in Drive](https://docs.google.com/document/d/1lxIvzeqQV4wQ6jG5IYtDTtn84fIJTCYCDwGaUSzBaTQ/edit#).🔒

### CODE REVIEW

**Comment by alexsoble** [comment]
@amymok and @carjug, tagging you as reviewers since we co-created this document together. I want to make sure we're all 👍  on it!

@ninamak, added you as a reviewer like we discussed earlier today. We want your thoughts and input from the PM & Project Lead points of view!

Still to be determined how closely our gov PO wants to review this work. At the very least I'd want to run these practices by her and discuss their importance together.

All reviewers can use the "Preview link" URL above to see how the markdown is rendered on GitHub.

**Review by carjug — APPROVED** [review]
This all looks good to me, Alex 👍

**Comment by carjug** [comment]
PS YAYYY first PR 🎉  @alexsoble

**Review by amymok — APPROVED** [review]
Looks great to me! 🎉

**Review by ninamak — APPROVED** [review]

**Comment by ninamak** [comment]
Looks great!!

**Comment by alexsoble** [comment]
@ninamak @carjug @amymok Whoever gets this notification first, could you please merge in this PR now that it has all 3 approvals? Going with "don't merge your own PR" politeness here! 😄 

We can run this document by our partner after it's merged and see if she has any questions or comments.

**Comment by carjug** [comment]
Merged! @alexsoble

**Pull request merged**
